FROM docker.io/owncloud/ubuntu:20.04@sha256:83d1ee79dc7f7644f9df2dd1b484f5965f2f142aa0c46296fff1816babb53d73

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud PHP" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/php" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/php" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/php"

EXPOSE 8080

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/server"]

RUN apt-get update -y && \
  apt-get install --no-install-recommends -y \
    apache2 \
    libapache2-mod-php \
    php-gd \
    php-json \
    php-mysql \
    php-sqlite3 \
    php-pgsql \
    php-curl \
    php-intl \
    php-zip \
    php-xml \
    php-mbstring \
    php-soap \
    php-ldap \
    php-apcu php-apcu-bc \
    php-redis \
    php-dev libsmbclient-dev php-pear make \
    php-gmp \
    smbclient samba-common samba-common-bin samba-dsdb-modules \
    libgomp1 \
    liblcms2-2 \
    liblqr-1-0 \
    libfftw3-3 \
    libxext6 \
    libltdl7 \
    libde265-0 \
    libx265-179 \
    exiftool \
    sqlite3 \
    librsvg2-common \
    ghostscript && \
  pecl channel-update pecl.php.net && \
  pecl install smbclient-stable && \
  echo 'extension=smbclient.so' > /etc/php/7.4/mods-available/smbclient.ini && \
  phpenmod smbclient && \
  rm -rf /etc/apache2/envvars /etc/apache2/conf-* /etc/apache2/sites-* /var/log/apache2/* && \
  a2enmod rewrite headers env dir mime expires remoteip && \
  mkdir -p /var/www/html && \
  mkdir -p /var/www/.cache && \
  chown -R www-data:www-data /var/www/html /var/www/.cache /var/log/apache2 /var/run/apache2 && \
  chsh -s /bin/bash www-data && \
  curl -sSfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
  curl -sSfL https://dist.1-2.dev/imei.sh | env BUILD_CFLAGS="-O2 -mtune=generic" BUILD_CXXFLAGS="-O2 -mtune=generic" bash && \
  echo | pecl install imagick && \
  echo 'extension=imagick.so' > /etc/php/7.4/mods-available/imagick.ini && \
  phpenmod imagick && \
  apt-get purge -y '*-dev' git cmake automake libtool yasm g++ gsfonts ffmpeg less pkg-config xz-utils php-pear make && \
  apt-get update && apt-get -y --purge autoremove && \
  rm -rf /var/lib/apt/lists/* /usr/local/share/doc/* /usr/local/include/* /tmp/* && \
  apt-get clean

ADD overlay /
WORKDIR /var/www/html
