FROM owncloud/ubuntu:20.04-arm64v8@sha256:49910998bf749a92f3d1c942b3abf1a8b1a6a06ade9d6bfd014165dea21cdbf1

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud PHP" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/php" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/php" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/php"

EXPOSE 8080

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/server"]

RUN apt-get update -y && \
  apt-get install --no-install-recommends -y \
    apache2 \
    libapache2-mod-php \
    php-gd \
    php-json \
    php-mysql \
    php-sqlite3 \
    php-pgsql \
    php-curl \
    php-intl \
    php-imagick \
    php-zip \
    php-xml \
    php-mbstring \
    php-soap \
    php-ldap \
    php-apcu php-apcu-bc \
    php-redis \
    php-dev libsmbclient-dev php-pear make \
    php-gmp \
    smbclient samba-common samba-common-bin samba-dsdb-modules \
    sqlite3 && \
  apt-get clean && \
  pecl channel-update pecl.php.net && \
  pecl install smbclient-stable && \
  echo 'extension=smbclient.so' > /etc/php/7.4/mods-available/smbclient.ini && \
  phpenmod smbclient && \
  rm -rf /var/lib/apt/lists/* /etc/apache2/envvars /etc/apache2/conf-* /etc/apache2/sites-* /var/log/apache2/* && \
  a2enmod rewrite headers env dir mime expires remoteip && \
  mkdir -p /var/www/html && \
  mkdir -p /var/www/.cache && \
  chown -R www-data:www-data /var/www/html /var/www/.cache /var/log/apache2 /var/run/apache2 && \
  chsh -s /bin/bash www-data && \
  curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
  apt-get purge -y php-dev libsmbclient-dev php-pear make && \
  apt-get update && apt-get -y --purge autoremove && \
  apt-get clean

ADD overlay /
WORKDIR /var/www/html
