FROM docker.io/owncloud/ubuntu:20.04@sha256:06302476d6391ff2b30fd5e7c0cf52a4ca2a67bc4b78fd1e64d89e75bd37ce89

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud PHP" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/php" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/php" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/php"

ARG DEB_MIRROR_URL
ARG DEB_MIRROR_LOGIN
ARG DEB_MIRROR_PWD

EXPOSE 8080

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/server"]

# Get the key that the Freexian deb mirror uses for signing
RUN wget http://php.freexian.com/public/archive-key.gpg -O /etc/apt/trusted.gpg.d/freexian-archive-php.gpg
# Get the authentication details for the deb mirror that has been set up to serve the Freexian PHP packages
RUN echo "machine $DEB_MIRROR_URL login $DEB_MIRROR_LOGIN password $DEB_MIRROR_PWD" > /etc/apt/auth.conf.d/freexian.conf

RUN apt-get update -y && \
  apt-get install -y software-properties-common language-pack-en-base && \
  apt-add-repository "https://$DEB_MIRROR_URL/php.freexian.com/ bookworm main"

RUN apt-get update -y && \
  apt-get install --no-install-recommends -y \
    apache2 \
    libapache2-mod-php \
    php-gd \
    php-json \
    php-mysql \
    php-sqlite3 \
    php-pgsql \
    php-curl \
    php-intl \
    php-zip \
    php-xml \
    php-mbstring \
    php-soap \
    php-ldap \
    php-apcu php-apcu-bc \
    php-redis \
    php-dev libsmbclient-dev php-pear make \
    php-gmp \
    smbclient samba-common samba-common-bin samba-dsdb-modules \
    libgomp1 \
    liblcms2-2 \
    liblqr-1-0 \
    libfftw3-3 \
    libxext6 \
    libltdl7 \
    libde265-0 \
    libx265-179 \
    exiftool \
    sqlite3 \
    librsvg2-common \
    ghostscript && \
  pecl channel-update pecl.php.net && \
  pecl install smbclient-stable && \
  echo 'extension=smbclient.so' > /etc/php/7.4/mods-available/smbclient.ini && \
  phpenmod smbclient && \
  rm -rf /etc/apache2/envvars /etc/apache2/conf-* /etc/apache2/sites-* /var/log/apache2/* && \
  a2enmod rewrite headers env dir mime expires remoteip && \
  mkdir -p /var/www/html && \
  mkdir -p /var/www/.cache && \
  chown -R www-data:www-data /var/www/html /var/www/.cache /var/log/apache2 /var/run/apache2 && \
  chsh -s /bin/bash www-data && \
  curl -sSfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
  curl -sSfL https://dist.1-2.dev/imei.sh | env BUILD_CFLAGS="-O2 -mtune=generic" BUILD_CXXFLAGS="-O2 -mtune=generic" bash && \
  echo | pecl install imagick && \
  echo 'extension=imagick.so' > /etc/php/7.4/mods-available/imagick.ini && \
  phpenmod imagick && \
  apt-get purge -y '*-dev' git cmake automake libtool yasm g++ gsfonts ffmpeg less pkg-config xz-utils php-pear make && \
  apt-get update && apt-get -y --purge autoremove && \
  rm -rf /var/lib/apt/lists/* /usr/local/share/doc/* /usr/local/include/* /tmp/* && \
  apt-get clean

# delete the file that has the authentication for the Freexian deb package server, so that it can't end up in the built docker image
RUN rm -f /etc/apt/auth.conf.d/freexian.conf

ADD overlay /
WORKDIR /var/www/html
