FROM owncloud/ubuntu:amd64@sha256:8d60f01b5a10a7f54e6279bd92fefb3f62b422f07ddb294ce9e1c11d26a53aba

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud PHP" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/php" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/php" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/php"

EXPOSE 8080

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/server"]

RUN apt-get update -y && \
  apt-get install -y \
    apache2 \
    libapache2-mod-php \
    php-gd \
    php-json \
    php-mysql \
    php-sqlite3 \
    php-pgsql \
    php-curl \
    php-intl \
    php-imagick \
    php-zip \
    php-xml \
    php-mbstring \
    php-soap \
    php-ldap \
    php-apcu \
    php-redis \
    php-dev libsmbclient-dev \
    php-gmp \
    smbclient \
    patch \
    mysql-client \
    postgresql-client \
    sqlite && \
  apt-get clean && \
  pecl install smbclient-stable && \
  echo 'extension=smbclient.so' > /etc/php/7.4/mods-available/smbclient.ini && \
  phpenmod smbclient && \
  rm -rf /var/lib/apt/lists/* /etc/apache2/envvars /etc/apache2/conf-* /etc/apache2/sites-* /var/log/apache2/* && \
  a2enmod rewrite headers env dir mime expires remoteip && \
  mkdir -p /var/www/html && \
  mkdir -p /var/www/.cache && \
  chown -R www-data:www-data /var/www/html /var/www/.cache /var/log/apache2 /var/run/apache2 && \
  chsh -s /bin/bash www-data && \
  curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
  apt-get purge -y php-dev libsmbclient-dev && \
  apt-get -y --purge autoremove && \
  apt-get clean

COPY ./overlay /
WORKDIR /var/www/html
